name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  python-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Set up venv
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install ruff mypy pytest
      - name: Run make ci (if present) or fallback
        run: |
          . .venv/bin/activate
          if [ -f Makefile ]; then
            make ci
          else
            ruff check .
            mypy --ignore-missing-imports .
            pytest -q || true
          fi
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            .pytest_cache
            logs/**
            coverage.xml
            junit.xml
          if-no-files-found: ignore

  terraform-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/terraform
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init -input=false
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Plan (plan-only)
        env:
          TF_VAR_aws_region: us-east-1
        run: terraform plan -input=false -out=tfplan
      - name: Upload tf plan
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: infra/terraform/tfplan
